spring.application.name=frontend-service

spring.restclient.uri.product_service=http://localhost:8081
spring.restclient.uri.user_service=http://localhost:8082
spring.mvc.hiddenmethod.filter.enabled=true