spring.application.name=user_service

spring.datasource.url=jdbc:postgresql://${USERS_DB_HOST:localhost}:${USERS_DB_PORT:5432}/${USERS_DB_NAME}
spring.datasource.username=${USERS_DB_USER}
spring.datasource.password=${USERS_DB_PASSWORD}

server.port=8082

jwt.token.secret=${JWT_SECRET}