spring.application.name=user_service
spring.datasource.url=jdbc:postgresql://${USERS_DB_HOST:localhost}:${USERS_DB_PORT:5432}/${USERS_DB_NAME}
spring.datasource.username=${USERS_DB_USER}
spring.datasource.password=${USERS_DB_PASSWORD}
server.port=8082
#logging.level.org.springframework.web.client.RestClient=INFO
#logging.level.org.apache.hc.client5.http=INFO
#logging.level.org.springframework.security=INFO
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:SuperSecretRedisPass2026!}
spring.cache.type=redis
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/merchly
keycloak.server-url=http://localhost:8090
keycloak.realm=merchly
keycloak.client-id=admin-cli
keycloak.admin-username=admin
keycloak.admin-password=admin
minio.url=${MINIO_URL}
minio.access.name=${MINIO_ACCESS_KEY}
minio.access.secret=${MINIO_SECRET_KEY}
minio.bucket.users=merchly-users
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB