spring.cloud.config.enabled=false
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
keycloak.server-url=http://localhost:8090
keycloak.realm=test-realm
keycloak.client-id=test-client
keycloak.admin-username=test-admin
keycloak.admin-password=test-admin
minio.url=http://localhost:9000
minio.access.name=test-access-key
minio.access.secret=test-secret-key
minio.bucket.users=test-users-bucket
spring.data.redis.host=localhost
spring.data.redis.port=6379
