ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS user_roles_user_id_fkey;

ALTER TABLE users DROP COLUMN IF EXISTS password;

ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS users_id_seq;
ALTER TABLE users ALTER COLUMN id TYPE VARCHAR(36) USING id::VARCHAR;

ALTER TABLE users
    ALTER COLUMN email SET NOT NULL,
    ALTER COLUMN gender SET NOT NULL,
    ALTER COLUMN birth_date SET NOT NULL;

ALTER TABLE user_roles ALTER COLUMN user_id TYPE VARCHAR(36) USING user_id::VARCHAR;

ALTER TABLE user_roles
    ADD CONSTRAINT user_roles_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;