spring.application.name=product-service

spring.datasource.url=jdbc:postgresql://${PRODUCTS_DB_HOST:localhost}:${PRODUCTS_DB_PORT:5433}/${PRODUCTS_DB_NAME:merchly_products}
spring.datasource.username=${PRODUCTS_DB_USER:products_admin}
spring.datasource.password=${PRODUCTS_DB_PASSWORD:SuperSecretProductsPass2026!}

server.port=8081