spring.cloud.config.enabled=false

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
spring.cache.type=simple
minio.bucket.products=merchly-products
minio.url=http://localhost:9000
minio.access.name=test-access-key
minio.access.secret=test-secret-key
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=product-service-group
spring.kafka.consumer.auto-offset-reset=earliest
app.kafka.topics.order-created=order-created
app.kafka.topics.order-failed=order-failed
app.kafka.topics.order-cancelled=order-cancelled
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/merchly