spring.application.name=product-service
spring.datasource.url=jdbc:postgresql://${PRODUCTS_DB_HOST:localhost}:${PRODUCTS_DB_PORT:5433}/${PRODUCTS_DB_NAME}
spring.datasource.username=${PRODUCTS_DB_USER}
spring.datasource.password=${PRODUCTS_DB_PASSWORD}
server.port=8081
jwt.token.secret=${JWT_SECRET}
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:SuperSecretRedisPass2026!}
spring.cache.type=redis