ALTER TABLE product
    ADD COLUMN price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    ADD CONSTRAINT chk_product_price CHECK (price > 0);

ALTER TABLE product
    ADD COLUMN created_by INT NOT NULL DEFAULT 0;

ALTER TABLE product
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE product
    ADD COLUMN is_available BOOLEAN NOT NULL DEFAULT TRUE;

CREATE INDEX idx_product_created_by ON product(created_by);