spring.cloud.config.server.git.uri=${CONFIG_REPO_URI:https://github.com/cvvexx/merchly-server-config}
spring.cloud.config.server.git.default-label=${CONFIG_REPO_BRANCH:master}
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.timeout=10
spring.cloud.config.server.git.basedir=${CONFIG_REPO_BASEDIR:/tmp/merchly-config-repo}
