spring.application.name=merchly-config-server
server.port=${CONFIG_SERVER_PORT:8888}
spring.profiles.active=${CONFIG_SERVER_PROFILE:git}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
spring.cloud.config.enabled=false
logging.level.org.springframework.cloud.config.server=INFO