spring.application.name=review-service
spring.datasource.url=jdbc:postgresql://${REVIEWS_DB_HOST:localhost}:${REVIEWS_DB_PORT:5435}/${REVIEWS_DB_NAME}
spring.datasource.username=${REVIEWS_DB_USER}
spring.datasource.password=${REVIEWS_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8083
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/merchly
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:SuperSecretRedisPass2026!}
spring.cache.type=redis