spring.application.name=review-service
spring.datasource.url=jdbc:postgresql://${REVIEWS_DB_HOST:localhost}:${REVIEWS_DB_PORT:5435}/${REVIEWS_DB_NAME}
spring.datasource.username=${REVIEWS_DB_USER}
spring.datasource.password=${REVIEWS_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8083